name: Deployment
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: nbl-altair/mepapp-docker/mepapp
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          # tags: "1.2"

  deploy:
      runs-on: ubuntu-latest
      needs: [ build ]
      steps:
        - name: Deploy
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PASSWORD }}
            passphrase: ${{ secrets.PASSPHRASE }}
            port: ${{ secrets.PORT }}
            script: |
              cd mepapp
              docker compose pull
              docker compose up -d 